/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesUniformRouteImport } from './routes/resources.uniform'
import { Route as ResourcesTermsRouteImport } from './routes/resources.terms'
import { Route as ResourcesHandbookRouteImport } from './routes/resources.handbook'
import { Route as ResourcesFaqRouteImport } from './routes/resources.faq'
import { Route as ResourcesCalendarRouteImport } from './routes/resources.calendar'
import { Route as NewsAwardsRouteImport } from './routes/news.awards'
import { Route as NewsAnnouncementsRouteImport } from './routes/news.announcements'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalHealthSafetyRouteImport } from './routes/legal.health-safety'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalChildProtectionRouteImport } from './routes/legal.child-protection'
import { Route as CareersVacanciesRouteImport } from './routes/careers.vacancies'
import { Route as AdmissionsApplyRouteImport } from './routes/admissions.apply'
import { Route as AboutVisionRouteImport } from './routes/about.vision'
import { Route as AboutValuesRouteImport } from './routes/about.values'
import { Route as AboutStaffRouteImport } from './routes/about.staff'
import { Route as AboutPoliciesRouteImport } from './routes/about.policies'

const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesUniformRoute = ResourcesUniformRouteImport.update({
  id: '/resources/uniform',
  path: '/resources/uniform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTermsRoute = ResourcesTermsRouteImport.update({
  id: '/resources/terms',
  path: '/resources/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesHandbookRoute = ResourcesHandbookRouteImport.update({
  id: '/resources/handbook',
  path: '/resources/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFaqRoute = ResourcesFaqRouteImport.update({
  id: '/resources/faq',
  path: '/resources/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCalendarRoute = ResourcesCalendarRouteImport.update({
  id: '/resources/calendar',
  path: '/resources/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAwardsRoute = NewsAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => NewsRoute,
} as any)
const NewsAnnouncementsRoute = NewsAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => NewsRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalHealthSafetyRoute = LegalHealthSafetyRouteImport.update({
  id: '/legal/health-safety',
  path: '/legal/health-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalChildProtectionRoute = LegalChildProtectionRouteImport.update({
  id: '/legal/child-protection',
  path: '/legal/child-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersVacanciesRoute = CareersVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => CareersRoute,
} as any)
const AdmissionsApplyRoute = AdmissionsApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutValuesRoute = AboutValuesRouteImport.update({
  id: '/about/values',
  path: '/about/values',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutStaffRoute = AboutStaffRouteImport.update({
  id: '/about/staff',
  path: '/about/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPoliciesRoute = AboutPoliciesRouteImport.update({
  id: '/about/policies',
  path: '/about/policies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/student-life': typeof StudentLifeRoute
  '/about/policies': typeof AboutPoliciesRoute
  '/about/staff': typeof AboutStaffRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision': typeof AboutVisionRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/careers/vacancies': typeof CareersVacanciesRoute
  '/legal/child-protection': typeof LegalChildProtectionRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/health-safety': typeof LegalHealthSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/awards': typeof NewsAwardsRoute
  '/resources/calendar': typeof ResourcesCalendarRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/handbook': typeof ResourcesHandbookRoute
  '/resources/terms': typeof ResourcesTermsRoute
  '/resources/uniform': typeof ResourcesUniformRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/student-life': typeof StudentLifeRoute
  '/about/policies': typeof AboutPoliciesRoute
  '/about/staff': typeof AboutStaffRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision': typeof AboutVisionRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/careers/vacancies': typeof CareersVacanciesRoute
  '/legal/child-protection': typeof LegalChildProtectionRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/health-safety': typeof LegalHealthSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/awards': typeof NewsAwardsRoute
  '/resources/calendar': typeof ResourcesCalendarRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/handbook': typeof ResourcesHandbookRoute
  '/resources/terms': typeof ResourcesTermsRoute
  '/resources/uniform': typeof ResourcesUniformRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/student-life': typeof StudentLifeRoute
  '/about/policies': typeof AboutPoliciesRoute
  '/about/staff': typeof AboutStaffRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision': typeof AboutVisionRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/careers/vacancies': typeof CareersVacanciesRoute
  '/legal/child-protection': typeof LegalChildProtectionRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/health-safety': typeof LegalHealthSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/awards': typeof NewsAwardsRoute
  '/resources/calendar': typeof ResourcesCalendarRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/handbook': typeof ResourcesHandbookRoute
  '/resources/terms': typeof ResourcesTermsRoute
  '/resources/uniform': typeof ResourcesUniformRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/admissions'
    | '/careers'
    | '/clubs'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/our-story'
    | '/student-life'
    | '/about/policies'
    | '/about/staff'
    | '/about/values'
    | '/about/vision'
    | '/admissions/apply'
    | '/careers/vacancies'
    | '/legal/child-protection'
    | '/legal/cookies'
    | '/legal/health-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/news/announcements'
    | '/news/awards'
    | '/resources/calendar'
    | '/resources/faq'
    | '/resources/handbook'
    | '/resources/terms'
    | '/resources/uniform'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admissions'
    | '/careers'
    | '/clubs'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/our-story'
    | '/student-life'
    | '/about/policies'
    | '/about/staff'
    | '/about/values'
    | '/about/vision'
    | '/admissions/apply'
    | '/careers/vacancies'
    | '/legal/child-protection'
    | '/legal/cookies'
    | '/legal/health-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/news/announcements'
    | '/news/awards'
    | '/resources/calendar'
    | '/resources/faq'
    | '/resources/handbook'
    | '/resources/terms'
    | '/resources/uniform'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/admissions'
    | '/careers'
    | '/clubs'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/our-story'
    | '/student-life'
    | '/about/policies'
    | '/about/staff'
    | '/about/values'
    | '/about/vision'
    | '/admissions/apply'
    | '/careers/vacancies'
    | '/legal/child-protection'
    | '/legal/cookies'
    | '/legal/health-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/news/announcements'
    | '/news/awards'
    | '/resources/calendar'
    | '/resources/faq'
    | '/resources/handbook'
    | '/resources/terms'
    | '/resources/uniform'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRouteWithChildren
  CareersRoute: typeof CareersRouteWithChildren
  ClubsRoute: typeof ClubsRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  StudentLifeRoute: typeof StudentLifeRoute
  AboutPoliciesRoute: typeof AboutPoliciesRoute
  AboutStaffRoute: typeof AboutStaffRoute
  AboutValuesRoute: typeof AboutValuesRoute
  AboutVisionRoute: typeof AboutVisionRoute
  LegalChildProtectionRoute: typeof LegalChildProtectionRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalHealthSafetyRoute: typeof LegalHealthSafetyRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ResourcesCalendarRoute: typeof ResourcesCalendarRoute
  ResourcesFaqRoute: typeof ResourcesFaqRoute
  ResourcesHandbookRoute: typeof ResourcesHandbookRoute
  ResourcesTermsRoute: typeof ResourcesTermsRoute
  ResourcesUniformRoute: typeof ResourcesUniformRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/uniform': {
      id: '/resources/uniform'
      path: '/resources/uniform'
      fullPath: '/resources/uniform'
      preLoaderRoute: typeof ResourcesUniformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/terms': {
      id: '/resources/terms'
      path: '/resources/terms'
      fullPath: '/resources/terms'
      preLoaderRoute: typeof ResourcesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/handbook': {
      id: '/resources/handbook'
      path: '/resources/handbook'
      fullPath: '/resources/handbook'
      preLoaderRoute: typeof ResourcesHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/faq': {
      id: '/resources/faq'
      path: '/resources/faq'
      fullPath: '/resources/faq'
      preLoaderRoute: typeof ResourcesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/calendar': {
      id: '/resources/calendar'
      path: '/resources/calendar'
      fullPath: '/resources/calendar'
      preLoaderRoute: typeof ResourcesCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/awards': {
      id: '/news/awards'
      path: '/awards'
      fullPath: '/news/awards'
      preLoaderRoute: typeof NewsAwardsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/announcements': {
      id: '/news/announcements'
      path: '/announcements'
      fullPath: '/news/announcements'
      preLoaderRoute: typeof NewsAnnouncementsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/health-safety': {
      id: '/legal/health-safety'
      path: '/legal/health-safety'
      fullPath: '/legal/health-safety'
      preLoaderRoute: typeof LegalHealthSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/child-protection': {
      id: '/legal/child-protection'
      path: '/legal/child-protection'
      fullPath: '/legal/child-protection'
      preLoaderRoute: typeof LegalChildProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/vacancies': {
      id: '/careers/vacancies'
      path: '/vacancies'
      fullPath: '/careers/vacancies'
      preLoaderRoute: typeof CareersVacanciesRouteImport
      parentRoute: typeof CareersRoute
    }
    '/admissions/apply': {
      id: '/admissions/apply'
      path: '/apply'
      fullPath: '/admissions/apply'
      preLoaderRoute: typeof AdmissionsApplyRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/about/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/values': {
      id: '/about/values'
      path: '/about/values'
      fullPath: '/about/values'
      preLoaderRoute: typeof AboutValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/staff': {
      id: '/about/staff'
      path: '/about/staff'
      fullPath: '/about/staff'
      preLoaderRoute: typeof AboutStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/policies': {
      id: '/about/policies'
      path: '/about/policies'
      fullPath: '/about/policies'
      preLoaderRoute: typeof AboutPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdmissionsRouteChildren {
  AdmissionsApplyRoute: typeof AdmissionsApplyRoute
}

const AdmissionsRouteChildren: AdmissionsRouteChildren = {
  AdmissionsApplyRoute: AdmissionsApplyRoute,
}

const AdmissionsRouteWithChildren = AdmissionsRoute._addFileChildren(
  AdmissionsRouteChildren,
)

interface CareersRouteChildren {
  CareersVacanciesRoute: typeof CareersVacanciesRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersVacanciesRoute: CareersVacanciesRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface NewsRouteChildren {
  NewsAnnouncementsRoute: typeof NewsAnnouncementsRoute
  NewsAwardsRoute: typeof NewsAwardsRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsAnnouncementsRoute: NewsAnnouncementsRoute,
  NewsAwardsRoute: NewsAwardsRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRouteWithChildren,
  CareersRoute: CareersRouteWithChildren,
  ClubsRoute: ClubsRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  StudentLifeRoute: StudentLifeRoute,
  AboutPoliciesRoute: AboutPoliciesRoute,
  AboutStaffRoute: AboutStaffRoute,
  AboutValuesRoute: AboutValuesRoute,
  AboutVisionRoute: AboutVisionRoute,
  LegalChildProtectionRoute: LegalChildProtectionRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalHealthSafetyRoute: LegalHealthSafetyRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ResourcesCalendarRoute: ResourcesCalendarRoute,
  ResourcesFaqRoute: ResourcesFaqRoute,
  ResourcesHandbookRoute: ResourcesHandbookRoute,
  ResourcesTermsRoute: ResourcesTermsRoute,
  ResourcesUniformRoute: ResourcesUniformRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
